project:
  type: book

book:
  title: "CHL5202 Winter 2025"
  author: "Lin Yu"
  date: "3/24/2025"
  chapters:
    - index.qmd
    - Tutorial1/Tut1.qmd
    - Tutorial2/Tut2.qmd
    - Tutorial3/Tut3.qmd
    - Tutorial4/Tut4.qmd
    - Tutorial5/Tut5.qmd
    - Tutorial6/Tut6.qmd
    - Tutorial7/Tut7.qmd
    - Tutorial8/Tut8.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



